name: Build and Test Pybind11 Module

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      id: py
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pybind11 (pip)
      run: pip install pybind11

    - name: Configure CMake
      run: |
        cmake -S . -B build -D"pybind11_DIR=$(python -m pybind11 --cmakedir)" -D"Python3_EXECUTABLE=${{ steps.py.outputs.python-path }}"

    - name: Build extension
      run: |
        cmake --build build --config Release
        cmake --install build

    - name: Run test script
      shell: bash
      run: |
        cp test.py *.txt dist/
        cd dist
        python test.py
